### ISSUE TITLE
buggy rounded corners on file manager / nautilus.

### ISSUE THREAD

**Issue by arun54321** [bR3iN/FlatWaita-16#1]
![image](https://user-images.githubusercontent.com/42943340/147640980-cb443752-6b61-4e8f-8e2f-c3a26a7a31b7.png)

**Comment by bR3iN** [comment]
Hi there!
Thanks for reaching out. I was able to reproduce this behavior with nautilus; however, this behavior is also present with the [gtk-3-24 Adwaita theme](https://gitlab.gnome.org/GNOME/gtk/tree/gtk-3-24/gtk/theme/Adwaita/), which this theme is simply a recoloring of. Originally, I didn't plan to make any changes to the theme aside from the recoloring (since my CSS and GTK knowledge is limited), but I will look more into this when I have more time at my disposal. As a workaround, for now, you can set
```css
decoration {
	box-shadow: none;
}
```
in your `~/.config/gtk-3.0/gtk.css` file as found [here](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland#removing-the-rounded-corners-and-dropshadow-of-themes-like-adwaita). However, this also removes natuilus's rounded corners. I hope this helps.

**Comment by arun54321** [comment]
[line 128](https://github.com/risiOS/Adwaita-recolor/blob/8007cac49d3c80fd91a2126541ad7abff58f7acf/adwaita-recolor#L128)

**Comment by bR3iN** [comment]
Hey, sorry for my late response.
The patch you linked to unfortunately didn't work for me (tested on Fedora 35). Have you tried it yourself? Did it work for you?
I just merged my own fix for the buggy corners; please let me know if it now also works for you.

**Comment by arun54321** [comment]
Thanks for fixing it. Top corners look good.
bottom corners still have that problem.

**Comment by arun54321** [comment]
I cannot take screenshot of it. It appear on moving windows.

https://user-images.githubusercontent.com/42943340/153631197-dfb87e69-ab90-40fc-91e2-dbcadeaec2ac.mp4

**Comment by arun54321** [comment]
screencapture - https://0x0.st/oXlV.mp4

**Comment by bR3iN** [comment]
That seems to come from a typo from my end. Thanks for pointing that out. It should be fixed now.

I also noticed that the buggy corners are present on all Gnome apps (Weather, Calender, etc.), not only on nautilus. The patch should now be applied to all windows, so those should now also look as expected.

**Comment by arun54321** [comment]
Corners now look sharp. (not rounded). Thank for fixing though.

**Comment by bR3iN** [comment]
If you're mostly concerned with nautilus, you can get back the rounded corners by creating a file at `~/.config/gtk-3.0/gtk.css` (if not already present) and adding
```CSS
.nautilus-window decoration {
    border-radius: 7px 7px 7px 7px;
}
```
to its contents. You might have to run `killall nautilus` from the terminal (or simply reboot) for nautilus to pick up the changes.

The problem I had were:
- Not only nautilus had the buggy corners, but almost all gnome applications.
- Simply applying the fix above to all applications (changing `.nautilus-window` -> `window`) would make the corners of other applications "buggy" (e.g. the Gnome Settings app).

So while I agree that it would be optimal to preserve all rounded corners present in the original Adwaita theme, I went with the current solution since it at least leaves all applications in a "non-buggy" state. But I will revisit the problem in the future.
